### ISSUE TITLE
null pointer exception when inputing user guess

### ISSUE THREAD

**Issue by Lewis-Matt** [Lewis-Matt/dot-com-killer#1]
Enter userGuess as any value (e.g. "A3", "a3", etc.) throws:

```
exception in thread "main" java.lang.NullPointerException
	at DotCom.checkYourself(DotCom.java:28)
	at DotComBust.checkUserGuess(DotComBust.java:47)
	at DotComBust.startPlaying(DotComBust.java:36)
	at DotComBust.main(DotComBust.java:74)
```

**Comment by Lewis-Matt** [comment]
Never set the location (hence NULL) of each dotcom, added:
dotComToSet.setLocationCells(newLocation);
